# Generated by Django 2.2.6 on 2019-10-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_zip', models.FileField(upload_to='upload/%Y/%m')),
            ],
            options={
                'verbose_name': '压缩包',
                'verbose_name_plural': '压缩包',
                'db_table': 'zip_info',
            },
        ),
    ]
